server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://booking-postgres:5432/tripdb-bookings}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3
management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.distribution.percentiles-histogram.http.server.requests=true
feign.user-service.url=${FEIGN_USER_SERVICE_URL:http://localhost:8081}
feign.itinerary-service.url=${FEIGN_ITINERARY_SERVICE_URL:http://localhost:8083}
feign.destination-service.url=${FEIGN_DESTINATION_SERVICE_URL:http://localhost:8082}
feign.booking-service.url=${FEIGN_BOOKING_SERVICE_URL:http://localhost:8080}
